name: my_app
on: push
jobs:
  payment_app:
    runs-on: ubuntu-latest
    steps:
      - name: fetching the github code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src